version: '3.8'

services:
  db:
    image: "postgres:latest"
    restart: "always"
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  adminer:
    image: "adminer"
    restart: "always"
    ports:
      - "8080:8080"
      
  app:
    build: "."
    image: "backend:latest"
    restart: "always"
    expose:
      - "80"
    ports:
      - "8000:8000"
    volumes:
      - ".:/usr/src/app"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_PORT=5432"
    command: bash -c "python3 manage.py runserver [::]:8000"
    depends_on:
      - "db"
